export enum NotificationType {
    TASK_ASSIGNED = 'TASK_ASSIGNED',
    DUE_DATE_REMINDER = 'DUE_DATE_REMINDER',
    STATUS_CHANGE = 'STATUS_CHANGE',
    COMMENT_MENTION = 'COMMENT_MENTION',
    NEW_COMMENT = 'NEW_COMMENT',
    INVITATION = 'INVITATION',
    PROJECT_CREATED = 'PROJECT_CREATED',
}
